### ISSUE TITLE
router.open for path not defined in routes config behaviour

### ISSUE THREAD

**Issue by Guria** [ai/nanostores#23]
Currently:
```
import { createRouter, keepActive, getValue } from "nanostores";

let router = createRouter({
  home: "/",
  foo: "/foo"
});
keepActive(router);
router.open("/bar");
console.log(getValue(router));
```
puts: `/bar` into addressbar and logs out `undefined` as value.
I haven't found tests about this so I am not sure if that intentional or not.

On one hand it isn't good to put store into "invalid" state, on the other hand user might already started on "/bar" route and we can't prevent it.

**Comment by ai** [comment]
Can you try `nanostores` 0.3.2? I fixed a very similar bug there.

**Comment by Guria** [comment]
> Can you try `nanostores` 0.3.2? I fixed a very similar bug there.

Checked with 0.3.2 and it still the same as expected, since problem lies in router part. It caused by parse returning `undefined` for routes not defined in config:

```js
router.open = (path, redirect) => {
  let page = parse(path)
  if (page !== false) {
    history[redirect ? 'replaceState' : 'pushState'](null, null, path)
    set(page)
  }
}
```
We have a check for `page !== false` which happens only when new path matches to previously parsed one. For `undefined` case we have history call with path as it was passed and set call with undefined. Which makes store to have "unexpected" state

**Comment by Guria** [comment]
Probably we might want to have some special state representing no match happened case.
We can introduce special route name value `"*"` and do smth like:
```
set(page || { path: path, route: "*", params: {} })
```

**Comment by ai** [comment]
> For undefined case we have history call with path as it was passed and set call with undefined.

It is by design. `getValue(router)` could return `undefined` (for 404). It will force TypeScript users to not forget about handling 404.
